In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv('Maternal Health Risk Data Set.csv')
print(df.head())

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [32]:
print("Rows: ", df.shape[0])
print("Columns: ", df.shape[1])

Rows:  1014
Columns:  7

In [33]:
df.dtypes

Age              int64
SystolicBP       int64
DiastolicBP      int64
BS             float64
BodyTemp       float64
HeartRate        int64
RiskLevel       object
dtype: object

In [34]:
df.isnull().sum()

Age            0
SystolicBP     0
DiastolicBP    0
BS             0
BodyTemp       0
HeartRate      0
RiskLevel      0
dtype: int64

In [35]:
df['RiskLevel'].value_counts().sort_index()

RiskLevel
high risk    272
low risk     406
mid risk     336
Name: count, dtype: int64

In [36]:
mapping = {'low risk': 0, 'mid risk': 1, 'high risk': 2}
df['RiskLevel'] = df['RiskLevel'].map(mapping)

In [37]:
df['RiskLevel']

0       2
1       2
2       2
3       2
4       0
       ..
1009    2
1010    2
1011    2
1012    2
1013    1
Name: RiskLevel, Length: 1014, dtype: int64

In [38]:
df.dtypes

Age              int64
SystolicBP       int64
DiastolicBP      int64
BS             float64
BodyTemp       float64
HeartRate        int64
RiskLevel        int64
dtype: object

In [39]:
df.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86          2
1   35         140           90  13.0      98.0         70          2
2   29          90           70   8.0     100.0         80          2
3   30         140           85   7.0      98.0         70          2
4   35         120           60   6.1      98.0         76          0

In [40]:
x = df.drop('RiskLevel', axis= 1)
y = df['RiskLevel']

In [41]:
print(x.shape)
print(y.shape)

(1014, 6)
(1014,)

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [43]:
print(x_train, x_test, y_train, y_test)

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
617    31         120           60   6.1      98.0         76
774    23         120           90   7.8      98.0         60
610    13          90           65   7.5     101.0         80
525    42         120           80   7.5      98.0         70
70     26          85           60   6.0     101.0         86
...   ...         ...          ...   ...       ...        ...
1012   43         120           90  18.0      98.0         70
481    22         100           65   7.9      98.0         80
458    34          85           60  11.0     102.0         86
309    60          90           65   6.9      98.0         77
326    66          85           60   6.9      98.0         86

[811 rows x 6 columns]      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
71    29         130           70   7.7      98.0         78
141   17          90           60   6.9     101.0         76
918   50         120           80   7.5      98.0         70
491   23         120           90   7.9      98.0         70
878   32         120           90   6.8      98.0         70
..   ...         ...          ...   ...       ...        ...
760   21          90           60   6.9      98.0         86
690   20         120           76   7.5      98.0         70
794   30         120           80   6.8      98.0         70
298   23          90           60   7.7      98.0         76
7     35          85           60  11.0     102.0         86

[203 rows x 6 columns] 617     0
774     1
610     2
525     0
70      1
       ..
1012    2
481     0
458     2
309     0
326     0
Name: RiskLevel, Length: 811, dtype: int64 71     1
141    1
918    0
491    1
878    0
      ..
760    1
690    0
794    1
298    0
7      2
Name: RiskLevel, Length: 203, dtype: int64

In [44]:
from sklearn.preprocessing import StandardScaler
scaler_standard = StandardScaler()
x_train_scaled = scaler_standard.fit_transform(x_train)
x_test_scaled = scaler_standard.transform(x_test)

In [45]:
y_train.value_counts(normalize=True)

RiskLevel
0    0.400740
1    0.331689
2    0.267571
Name: proportion, dtype: float64

In [50]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter= 5000)
lr_model.fit(x_train_scaled, y_train)

LogisticRegression(max_iter=5000)

In [51]:
lr_predictions = lr_model.predict(x_test_scaled)

In [52]:
print("Predictions (first 20):")
print(lr_predictions[:20])

print("\nActual values (first 20):")
print(y_test.values[:20])

from sklearn.metrics import accuracy_score
lr_accuracy = accuracy_score(y_test, lr_predictions)
print(lr_accuracy)

from sklearn.metrics import classification_report
cr = classification_report(y_test, lr_predictions, target_names=["GREEN", "YELLOW", "RED"])
print(cr)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(lr_model, x, y, cv=5)
print(scores)
print(scores.mean())

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, lr_predictions)
print (cm)

Predictions (first 20):
[1 1 0 0 0 0 2 0 0 1 0 2 0 1 2 0 0 0 2 2]

Actual values (first 20):
[1 1 0 1 0 0 2 0 1 1 0 2 0 0 2 0 0 0 2 2]
0.6403940886699507
              precision    recall  f1-score   support

       GREEN       0.65      0.77      0.70        81
      YELLOW       0.48      0.34      0.40        67
         RED       0.76      0.82      0.79        55

    accuracy                           0.64       203
   macro avg       0.63      0.64      0.63       203
weighted avg       0.62      0.64      0.63       203

[0.68472906 0.62561576 0.60098522 0.53694581 0.59405941]
0.6084670536019119
[[62 16  3]
 [33 23 11]
 [ 1  9 45]]

In [53]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(x_train_scaled, y_train)

dt_predictions = dt_model.predict(x_test_scaled)
print("Predictions (first 20):")
print(dt_predictions[:20])

print("\nActual values (first 20):")
print(y_test.values[:20])

from sklearn.metrics import accuracy_score
dt_accuracy = accuracy_score(y_test, dt_predictions)
print(dt_accuracy)

from sklearn.metrics import classification_report
cr = classification_report(y_test, dt_predictions, target_names=["GREEN", "YELLOW", "RED"])
print(cr)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(dt_model, x, y, cv=5)
print(scores)
print(scores.mean())

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, dt_predictions)
print (cm)

Predictions (first 20):
[1 1 0 1 0 0 2 0 1 1 1 2 0 0 2 1 1 1 2 2]

Actual values (first 20):
[1 1 0 1 0 0 2 0 1 1 0 2 0 0 2 0 0 0 2 2]
0.8374384236453202
              precision    recall  f1-score   support

       GREEN       0.85      0.79      0.82        81
      YELLOW       0.77      0.79      0.78        67
         RED       0.90      0.96      0.93        55

    accuracy                           0.84       203
   macro avg       0.84      0.85      0.84       203
weighted avg       0.84      0.84      0.84       203

[0.92610837 0.71428571 0.75369458 0.75862069 0.87623762]
0.8057893966736576
[[64 16  1]
 [ 9 53  5]
 [ 2  0 53]]

In [62]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(x_train_scaled, y_train)
rf_predictions = rf_model.predict(x_test_scaled)
dt_predictions = dt_model.predict(x_test_scaled)

print("Predictions (first 20):")
print(rf_predictions[:20])

print("\nActual values (first 20):")
print(y_test.values[:20])

rf_accuracy = accuracy_score(y_test, rf_predictions)
print(rf_accuracy)
cr = classification_report(y_test, rf_predictions, target_names=["LOW", "MID", "HIGH"])
print(cr)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf_model, x, y, cv=5)
print(scores)
print(scores.mean())

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, rf_predictions)
print (cm)

Predictions (first 20):
[1 1 0 1 0 0 2 0 1 1 1 2 0 0 2 0 1 1 2 2]

Actual values (first 20):
[1 1 0 1 0 0 2 0 1 1 0 2 0 0 2 0 0 0 2 2]
0.8522167487684729
              precision    recall  f1-score   support

         LOW       0.87      0.81      0.84        81
         MID       0.79      0.81      0.80        67
        HIGH       0.90      0.96      0.93        55

    accuracy                           0.85       203
   macro avg       0.85      0.86      0.86       203
weighted avg       0.85      0.85      0.85       203

[0.91133005 0.72413793 0.81773399 0.78325123 0.87623762]
0.822538165146564
[[66 14  1]
 [ 8 54  5]
 [ 2  0 53]]

In [56]:
from sklearn.metrics import roc_auc_score
y_prob = rf_model.predict_proba(x_test_scaled)

auc_score = roc_auc_score(
    y_test,
    y_prob,
    multi_class='ovr',
    average='macro'
)

print("ROC-AUC Score:", auc_score)

ROC-AUC Score: 0.9569083313286998

In [57]:
import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': x.columns,
    'Importance': rf_model.feature_importances_
}).sort_values('Importance', ascending=False)

print(feature_importance)

       Feature  Importance
3           BS    0.365753
1   SystolicBP    0.181902
0          Age    0.162947
2  DiastolicBP    0.128656
5    HeartRate    0.099203
4     BodyTemp    0.061539

In [58]:
def get_confidence(probabilities):
  max_prob = max(probabilities)

  if max_prob >= 0.8:
    return "HIGH CONFIDENCE"
  elif max_prob >= 0.6:
    return "LOW CONFIDENCE - SUGGEST REVIEW"
  else:
    return "UNCERTAIN - ESCALATE TO SENIOR WORKER"

In [59]:
print(x.columns.tolist())

['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate']

In [60]:
feature_names = ['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate']

def predict_triage(patient_vitals):
    vitals_df = pd.DataFrame([patient_vitals], columns=feature_names)
    vitals_scaled = scaler_standard.transform(vitals_df)
    probabilities = rf_model.predict_proba(vitals_scaled)[0]
    predicted_class = rf_model.predict(vitals_scaled)[0]
    confidence = get_confidence(probabilities)

    triage_map = {
        0: "Low Risk",
        1: "Mid Risk",
        2: "High Risk"
    }

    decision = triage_map[predicted_class]

    print("\n   INSIGHTHER ASSESSMENT")
    print("-----------------------------------")
    print(f"DECISION:    {decision}")
    print(f"CONFIDENCE:  {confidence}")
    print("--------------------------------")
    print(f"Low Risk:       {probabilities[0]:.1%}")
    print(f"Mid Risk:      {probabilities[1]:.1%}")
    print(f"High Risk:         {probabilities[2]:.1%}")
    print("--------------------------------\n")

    return {
        "triage": decision,
        "confidence": confidence,
        "probabilities": {
            "Low Risk": round(probabilities[0], 3),
            "Mid Risk": round(probabilities[1], 3),
            "High Risk": round(probabilities[2], 3)
        }
    }

In [61]:
patient_1 = [
    13, 99, 70, 20, 50, 60
]

predict_triage(patient_1)

   INSIGHTHER ASSESSMENT
-----------------------------------
DECISION:    High Risk
CONFIDENCE:  LOW CONFIDENCE - SUGGEST REVIEW
--------------------------------
Low Risk:       9.0%
Mid Risk:      23.4%
High Risk:         67.6%
--------------------------------

{'triage': 'High Risk',
 'confidence': 'LOW CONFIDENCE - SUGGEST REVIEW',
 'probabilities': {'Low Risk': np.float64(0.09),
  'Mid Risk': np.float64(0.234),
  'High Risk': np.float64(0.676)}}